[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# Все правила: https://docs.astral.sh/ruff/rules/
# Добавлять по мере надобности
extend-select = ["B", "Q", "ASYNC", "E"]
ignore = ["F401", "ASYNC110"]

fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.params.Depends",
    "fastapi.Query",
    "fastapi.params.Query",
    "fastapi.File",
    "fastapi.params.File",
]

[tool.pyright]
venvPath = "."
venv = "venv"
typeCheckingMode = "basic"
pythonVersion = "3.10"

[tool.isort]
profile = "black"
line_length = 100
py_version = 310
virtual_env = "venv"

sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
